### ISSUE TITLE
Error while moving file: Destination path '/Users/tristan/Desktop/UNI/' already exists```

### ISSUE THREAD

**Issue by Tristan296** [Tristan296/FileManager#1]
Every time I run my code when searching for a file, it finds the file and its directory, however, when I try to move the file to a different folder in my desktop I get an error stating that the folder already exists. I have tried creating new folders and moving other files but the issue persists. I think the issue is how the directory is set up in macOS. 
```
tristan@Tristans-MacBook-Pro FileManager % /usr/bin/python3 /Users/tristan/Di
eManager/FileManager.py
Enter 'move' to move a file, 'open' to search and open a file, or 'search' to search the entire computer: search
Enter the file name to search: chungus
Enter the file type: txt
File found at: /System/Volumes/Data/Users/tristan/Desktop/chungus.txt
What do you want to do with the file? (move/open/search)move
Create a new Folder (Y/N) : N
------------------------------------------------------------------------------------------
What is the parent of this folder : Desktop 
------------------------------------------------------------------------------------------
Enter folder name to move file into : UNI
------------------------------------------------------------------------------------------
destination path /Users/tristan/Desktop/UNI
Are you sure you want to do this? (Y/N) : Y
------------------------------------------------------------------------------------------
Error while moving file: Destination path '/Users/tristan/Desktop/UNI/' already exists```

**Comment by PotuRevanth** [comment]
> Every time I run my code when searching for a file, it finds the file and its directory, however, when I try to move the file to a different folder in my desktop I get an error stating that the folder already exists. I have tried creating new folders and moving other files but the issue persists. I think the issue is how the directory is set up in macOS.
> 
> ```
> tristan@Tristans-MacBook-Pro FileManager % /usr/bin/python3 /Users/tristan/Di
> eManager/FileManager.py
> Enter 'move' to move a file, 'open' to search and open a file, or 'search' to search the entire computer: search
> Enter the file name to search: chungus
> Enter the file type: txt
> File found at: /System/Volumes/Data/Users/tristan/Desktop/chungus.txt
> What do you want to do with the file? (move/open/search)move
> Create a new Folder (Y/N) : N
> ------------------------------------------------------------------------------------------
> What is the parent of this folder : Desktop 
> ------------------------------------------------------------------------------------------
> Enter folder name to move file into : UNI
> ------------------------------------------------------------------------------------------
> destination path /Users/tristan/Desktop/UNI
> Are you sure you want to do this? (Y/N) : Y
> ------------------------------------------------------------------------------------------
> Error while moving file: Destination path '/Users/tristan/Desktop/UNI/' already exists```
> ```
#TRY THIS#
If you can't move or copy a file or folder, you might need to change its permissions settings. You might also need to change permissions settings for the disk, server or folder where you want to move the item. On your Mac, select the item, then choose File > Get Info or press Command-I.

**Comment by Tristan296** [comment]
Hi, I found the solution! The problem was that I wasn't using the file variable ```filepath``` from the resulting variable after finding it with the search function. I checked my permissions for the folders and files that I was moving but all had read and write permissions. This is the result now:
Enter 'move' to move a file, 'open' to search and open a file, or 'search' to search the entire computer: search
Enter the file name to search: file123
Enter the file type: html
File found at: /System/Volumes/Data/Users/tristan/Desktop/file123.html
What do you want to do with the file? (move/open/search)move
Create a new Folder (Y/N) : N
------------------------------------------------------------------------------------------
What is the parent of this folder : Desktop
------------------------------------------------------------------------------------------
Enter folder name to move file into : FileManager
------------------------------------------------------------------------------------------
destination path /Users/tristan/Desktop/FileManager
Are you sure you want to do this? (Y/N) : y
------------------------------------------------------------------------------------------
File moved successfully!
