### ISSUE TITLE
❤ the screenshot in your readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [Tristan296/FileManager#8]
Was great to see you've dropped a screenshot into your readme.  Nothing gets attention like an image.  Well done looking interface too.

![image](https://user-images.githubusercontent.com/46163555/233858637-f1b818c0-edbf-4d3c-9479-e755f7e64084.png)

**Comment by PySimpleGUI** [comment]
If you want to expand your interface in the future to include a file list using a `Listbox`, then the `psgtest` utility may be a good source of sample code.  It's one way to working with files.  Both the Demo Browser and psgtest use a Listbox to display a list of files.  Searching is done using an Input element.  psgtest is the simpler of the two programs to look at as the Demo Browser has a search option that searches inside the files, overkill for a basic file manager.

![psgtest](https://user-images.githubusercontent.com/46163555/233859005-f5467a5d-c2c0-426b-9949-b3e4fc4a346c.gif)

This basic construct of using a Listbox to show and select files can be used in numerous ways.  For example, I have a little utility I use to release Demo Programs to GitHub that allows me to copy files, compare them, etc.  It's the same underlying logic.  Rather than showing the contents of 1 folder, it's showing the contents of 3.

![image](https://user-images.githubusercontent.com/46163555/233859135-95e38024-7a7c-400b-87a5-fcfb7f6fa18c.png)

There are some Demo Programs that show files using a Tree Element so that you can have collapsible folder contents also that you may want to look at when you're ready to expand what you've got.

**Comment by Tristan296** [comment]
Hi @PySimpleGUI, thank you for looking at my program and the suggestions, I really appreciate it. I made quite a few upgrades today. I have taken on your suggestion for implementing `ListBox` into the file manager but I've run into a few issues. I'm trying to make it so that after selecting a folder to browse in when searching for files, the ListBox will show all the files in the folder chosen.
